/**
 * @file Eng_MctCode.c
 * @brief Source code generated by MCT
 * MCT IDENTIFY
 *
 * @date 2004-11-2
 * @version 2.0
 */

/**
 * @include "Eng_KeyMapping.h"
 *
 */
#include "Eng_KeyMapping.h"
#include "gbl_global.h"
/*******************************************************************************
*
* Key mapping
*
*******************************************************************************/

/**
 * @brief Public
 *
 * @author MMI Configuration Tool
 * @date 2004-11-2
 * @param T_MMI_KEYPAD phyKey: physical key ID
 * @return T_eFUNC_KEY
 * @retval 
 */
T_eFUNC_KEY MappingPublicKey(T_MMI_KEYPAD phyKey)
{
    if (phyKey.pressType == PRESS_SHORT)
    {
        switch (phyKey.keyID) {
        case kbVOICE_UP:        return fkPUBLIC_VOICE_UP;
        case kbVOICE_DOWN:      return fkPUBLIC_VOICE_DOWN;
#ifdef CHRONTEL
		case kbSWX: 			return fkPUBLIC_TV_EN;
		case kbSWY: 			return fkPUBLIC_TV_SWITCH;
		
#endif

#ifdef SUPPORT_TVOUT        
        case kbSWX:             return fkPUBLIC_TV_EN;
        case kbSWY:             return fkPUBLIC_TV_SWITCH;
#endif        
        default:                break;
        }
    } 
    else if (phyKey.pressType == PRESS_LONG)    /* hold */
    {
        switch (phyKey.keyID) {
#if (defined(SPIBOOT) && defined(SUPPORT_TVOUT))
		case kbVOICE_UP:		return fkPUBLIC_TV_EN;
		case kbVOICE_DOWN:		return fkPUBLIC_TV_SWITCH;
#else
#ifdef CHIP_AK3753
        case kbVOICE_UP:        return fkPUBLIC_TV_EN;
        case kbVOICE_DOWN:      return fkPUBLIC_TV_SWITCH;
#else
	    case kbVOICE_UP:        return fkPUBLIC_VOICE_UP;
        case kbVOICE_DOWN:      return fkPUBLIC_VOICE_DOWN;
#endif
#endif
//      case kbCLEAR:           return fkPUBLIC_POWER_OFF;
        case kbMENU:            return fkPUBLIC_KEY_LOCK;

        default:                break;
        }
    }
    return fkNULL;
} /* end MappingPublicKey(T_MMI_KEYPAD phyKey) */

/**
 * @brief Sleep
 *
 * @author MMI Configuration Tool
 * @date 2004-11-2
 * @param T_MMI_KEYPAD phyKey: physical key ID
 * @return T_eFUNC_KEY
 * @retval 
 */
T_eFUNC_KEY MappingSleepKey(T_MMI_KEYPAD phyKey)
{
    if (phyKey.pressType == PRESS_SHORT)
    {
        switch (phyKey.keyID) {
        default:                break;
        }
    }
    else if (phyKey.pressType == PRESS_LONG)    /* hold */
    {
        switch (phyKey.keyID) {
        case kbCLEAR:           return fkSLEEP_POWER_ON;
        default:                break;
        }
    }
    return fkNULL;
} /* end MappingSleepKey(T_MMI_KEYPAD phyKey) */

/**
 * @brief Stand By
 *
 * @author MMI Configuration Tool
 * @date 2004-11-2
 * @param T_MMI_KEYPAD phyKey: physical key ID
 * @return T_eFUNC_KEY
 * @retval 
 */
T_eFUNC_KEY MappingStdbyKey(T_MMI_KEYPAD phyKey)
{
    if (phyKey.pressType == PRESS_SHORT)
    {
        switch (phyKey.keyID) {
        case kbUP:              return fkSTDBY_MENU;
        case kbDOWN:            return fkSTDBY_HIDE_BAR;
        case kbLEFT:            return fkSTDBY_MENU;
        case kbRIGHT:           return fkSTDBY_MENU;
        case kbOK:              return fkSTDBY_MENU;
        case kbMENU:            return fkSTDBY_MENU;
        default:                break;
        }
    }
    else if (phyKey.pressType == PRESS_LONG)    /* hold */
    {
        switch (phyKey.keyID) {
        case kbCLEAR:           return fkSTDBY_POWEROFF;
        default:                break;
        }
    }
    return fkNULL;
} /* end MappingStdbyKey(T_MMI_KEYPAD phyKey) */

/**
 * @brief Menu
 *
 * @author MMI Configuration Tool
 * @date 2004-11-2
 * @param T_MMI_KEYPAD phyKey: physical key ID
 * @return T_eFUNC_KEY
 * @retval 
 */
T_eFUNC_KEY MappingMenuKey(T_MMI_KEYPAD phyKey)
{
    if (phyKey.pressType == PRESS_SHORT)
    {
        switch (phyKey.keyID) {
        case kbUP:              return fkMENU_UP_LINE;
        case kbDOWN:            return fkMENU_DOWN_LINE;
        case kbLEFT:            return fkMENU_UP_ITEM;
        case kbRIGHT:           return fkMENU_DOWN_ITEM;
        case kbOK:              return fkMENU_SELECT;
        case kbCLEAR:           return fkMENU_EXIT;
        default:                break;
        }
    }
    else if (phyKey.pressType == PRESS_LONG)    /* hold */
    {
        switch (phyKey.keyID) {
        case kbUP:              return fkMENU_UP_LINE;
        case kbDOWN:            return fkMENU_DOWN_LINE;
        case kbLEFT:            return fkMENU_UP_ITEM;
        case kbRIGHT:           return fkMENU_DOWN_ITEM;
        case kbCLEAR:           return fkMENU_HOME;
        default:                break;
        }
    }
    return fkNULL;
} /* end MappingMenuKey(T_MMI_KEYPAD phyKey) */

/**
 * @brief Message Box
 *
 * @author MMI Configuration Tool
 * @date 2004-11-2
 * @param T_MMI_KEYPAD phyKey: physical key ID
 * @return T_eFUNC_KEY
 * @retval 
 */
T_eFUNC_KEY MappingMsgboxKey(T_MMI_KEYPAD phyKey)
{
    if (phyKey.pressType == PRESS_SHORT)
    {
        switch (phyKey.keyID) {
        case kbUP:              return fkMBOX_UP_LINE;
        case kbDOWN:            return fkMBOX_DOWN_LINE;
        case kbLEFT:            return fkMBOX_BUTTON_LEFT;
        case kbRIGHT:           return fkMBOX_BUTTON_RIGHT;
        case kbOK:              return fkMBOX_COMPLETE;
        case kbCLEAR:           return fkMBOX_EXIT;
        default:                break;
        }
    }
    else if (phyKey.pressType == PRESS_LONG)    /* hold */
    {
        switch (phyKey.keyID) {
        case kbUP:              return fkMBOX_UP_PAGE;
        case kbDOWN:            return fkMBOX_DOWN_PAGE;
        case kbCLEAR:           return fkMBOX_HOME;
        default:                break;
        }
    }
    return fkNULL;
} /* end MappingMsgboxKey(T_MMI_KEYPAD phyKey) */

#ifdef CAMERA_SUPPORT
/***********************************************************************************
FUNC NAME: MappingCameraKey
DESCRIPTION: mapping capture key
INPUT:
OUTPUT:
RETURN: 
AUTHOR:zhengwenbo
CREATE DATE:2006-6-27
MODIFY LOG:
***********************************************************************************/
T_eFUNC_KEY MappingCameraKey(T_MMI_KEYPAD phyKey)
{
    if (phyKey.pressType == PRESS_SHORT)
    {
        switch (phyKey.keyID) 
        {
            case kbMENU:                return fkCAMERA_MENU;
            case kbLEFT:                return fkCAMERA_ZOOM_OUT;
            case kbRIGHT:               return fkCAMERA_ZOOM_IN;       
            case kbOK:                  return fkCAMERA_CAPTURE;
            case kbCLEAR:               return fkCAMERA_EXIT;
            case kbUP:                  return fkCAMERA_SWICH_2_DC;
            case kbDOWN:                return fkCAMERA_SWICH_2_DV;
            default:                    break;
        }
    }

    return fkNULL;
}
#endif


/**
 * @brief mapping ebook key
 *
 * @author Heying
 * @date 2007-12-5
 * @param T_MMI_KEYPAD phyKey: physical key ID
 * @return T_EB_ACTION
 * @retval 
 */

T_EB_ACTION MappingEbookKey(T_MMI_KEYPAD phyKey)
{
    if (phyKey.pressType == PRESS_SHORT)
    {
        switch (phyKey.keyID)
        {
            case kbUP:
                return EB_UP_LINE;
            case kbDOWN:
                return EB_DOWN_LINE;
            case kbLEFT:
                return EB_UP_PAGE;
            case kbRIGHT:
                return EB_DOWN_PAGE;
            case kbOK:
                return EB_DOWN_PAGE;
            case kbCLEAR:
                return EB_RETURN;
            case kbMENU:
                return EB_MENU;
            default:
                break;
        }
    }
    else if (phyKey.pressType == PRESS_LONG)    /* hold */
    {
        switch (phyKey.keyID)
        {
            case kbUP:
                return EB_GO_TOP;
            case kbDOWN:
                return EB_DOWN_LINE;
            case kbLEFT:
                return EB_UP_PAGE;
            case kbRIGHT:
                return EB_DOWN_PAGE;
            case kbCLEAR:
                return EB_RETURN_HOME;
            case kbOK:
                return EB_GO_TOP;
            default:
                break;
        }
    }
    return 0;
}                               /* end MappingEbookKey(T_MMI_KEYPAD phyKey) */

